branches:
  only:
    - master
    - /^v[0-9]\.[0-9]\.[0-9]$/

sudo: required

services:
  - docker

language: node_js

node_js:
  - "4.4"

env:
  - DOCKER_IMAGE_NAME=spacehellas/tnova-vim-backend

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t $DOCKER_IMAGE_NAME .
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
      docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
    fi
  - docker push $DOCKER_IMAGE_NAME
