tsdb:
  image: tutum/influxdb:0.9
  environment:
    - PRE_CREATE_DB=statsdb
    - COLLECTD_DB=statsdb
    - COLLECTD_BINDING=:8096
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8096:8096/udp"
  volumes:
    - /srv/docker/tnova_vim/tsdb:/data
tnova-monitoring:
  image: tnova/vim-backend:latest
  environment:
    - LOGGING_LEVEL=info
    - CEILOMETER_HOST=localhost
    - CEILOMETER_PORT=8777
    - NOVA_HOST=localhost
    - NOVA_PORT=8774
    - IDENTITY_HOST=localhost
    - IDENTITY_PORT=5000
    - IDENTITY_TENANT=tenant
    - IDENTITY_USERNAME=username
    - IDENTITY_PASSWORD=pass
  links:
    - tsdb:influxdb
  ports:
    - "8080:3000"
visualisation:
  image: grafana/grafana
  ports:
    - "3000:3000"
